web-eid-auth-token:
  validation:
    use-digi-doc4j-prod-configuration: true
    local-origin: "https://web-eid.eu"
    truststore-password: "changeit"
web-eid-mobile:
    base-request-uri: "web-eid-mobile://"
    request-signing-cert: false
spring:
  thymeleaf:
    cache: true
